name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: 
        docker build . --file Dockerfile --tag fluentd:latest
        docker tag fluentd:latest ifreecomm/fluentd:v1.10.1
        docker login -u kangliqi -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push docker push ifreecomm/fluentd:v1.10.1
